/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String arg[]) {
<<<<<<< HEAD
    	System.out.println("hello world");
    	/*good work*/
=======
    	System.out.println("hello ");
>>>>>>> branch 'master' of https://github.com/kjiangab/lab8.git
    }
    public boolean someLibraryMethod() {
    	return true;
    } 
}
